### ISSUE TITLE
Errno 28

### ISSUE THREAD

**Issue by MauryaShraddha** [domoritz/streamlit-docker#1]
Hello,

When I execute the command: `docker-compose up`
After some downloads I get the following error:

`ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device
ERROR: Service 'streamlit' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1`

Can you please help me resolve this error?

**Comment by domoritz** [comment]
Looks like it may be an issue with docker. I don’t have cycles to help with the issue right now.
