### ISSUE TITLE
Cannot view the app in browser

### ISSUE THREAD

**Issue by MauryaShraddha** [domoritz/streamlit-docker#2]
I executed the `docker-compose run streamlit black src/` command and got the following output: 
`reformatted src/main.py
All done! ✨ 🍰 ✨
1 file reformatted.`

Next I executed the `docker-compose up` command and got the following output: 
`Starting streamlit-docker-master_streamlit_1 ... done                                                                   Attaching to streamlit-docker-master_streamlit_1
streamlit_1  |
streamlit_1  |   You can now view your Streamlit app in your browser.
streamlit_1  |
streamlit_1  |   Network URL: http://172.19.0.2:8501`

But I can't view any app output in the browser. When I try to open the link: http://localhost:8501/?name=main, it says the site can't be reached.

Can you please help me resolve this?

Thank you

**Comment by domoritz** [comment]
@jrhone suggests that you look at https://docs.streamlit.io/en/latest/troubleshooting/not-loading.html?highlight=enablecors#symptom-2-the-app-says-please-wait-forever.

I'm going to archive this repo since Streamlit is simple enough that it usually doesn't need a docker setup.
